使用go:embed嵌入静态资源
cloudreve/Cloudreve pull request #1107
Opened 2022-01-03 18:41 UTC by Ink-33

此Pull request为cloudreve引入以下几项更新
1. 将项目最低`go`版本提升至1.16
    - 已更改`go.mod`声明
    - 已更改`README.md`声明（待push）
    - 已更改actions脚本（使用`go 1.17.5`）
    - 已更改`Dockerfile`（需要测试是否可用）
    - 已更改`travis.yml`（需要测试是否可用）
    - 已将`ioutil`包改为使用其他包
2. 不再使用`statik`嵌入静态资源，改为使用 go1.16+ 提供的`go:embed`
    - 已更改`README.md`中构建说明（待push）
    - 已更改各种编译脚本
3. 改进了一些代码格式（使用`golangci-lint`）
4. 优化编译脚本以减小二进制文件体积（`Window-amd64` 33.6 MB，对比release中`3.4.2` 58.7MB）
    - `build.sh`默认删除`SourceMap`，与`statik`的嵌入行为保持一致
    - `build.sh`中添加`-ldflags "-s -w"`
5. 修复了单元测试中`/api/v3/site/ping/`失败的问题

本次更新**仅**修改了编译流程，当`Go<=1.16`的时将无法编译。`Go>=1.16`时，即使使用旧编译脚本（statik嵌入）也不会导致编译失败。用户对于此更新的感知理论上有go版本的更新而带来的一定的性能提升以及更小的二进制文件。

2022-01-21 17:21 UTC, Ink-33 commented
可能要用`testing.(*T).TempDir`重构单元测试，自动清理单元测试生成的文件
现在这单元测试在不同地方跑的结果还不一样。。
另外，用golangci-lint扫了一遍，发现存在大量无效变量和copylocks，以及很多未检查的错误，这些都应该纠正

2022-01-21 18:05 UTC, wangxiaoerYah commented
nb啊，大佬，这么晚还在忙。点赞

2022-02-19 05:35 UTC, topjohncian commented
建议拆分提交

2022-02-19 05:41 UTC, Ink-33 commented
好哦

2022-03-09 14:40 UTC, topjohncian commented
@HFO4 已升级到 Go 1.17 ，可尝试使用 `go:embed` 嵌入静态资源

2022-03-13 02:45 UTC, Ink-33 commented
请review

2022-03-13 06:28 UTC, HFO4 requested changes

2022-03-13 06:28 UTC, HFO4 commented on .travis.yml
> +  - touch test.html
可精简为
```
  - mkdir assets/build
  - touch assets/build/test.html
```
`test.yaml` 同理

2022-03-13 06:28 UTC, HFO4 commented on README.md
> +cd build
可在 README 中移除这段说明，移到文档里。

2022-03-13 06:28 UTC, HFO4 commented on README.md
> +当前版本无需手动嵌入静态资源，请直接进行下一步。
这段直接移除即可

2022-03-13 06:28 UTC, HFO4 commented on README.md
> +cd ../
可移除

2022-03-13 06:28 UTC, HFO4 commented on bootstrap/static.go
> +		StaticFS.(*GinFS).FS = http.FS(embedFS)
可简化为
```golang
StaticFS = &GinFS{
    FS:http.FS(embedFS),
}
```

2022-03-13 06:28 UTC, HFO4 commented on bootstrap/static.go
> +		util.Log().Error("导出内置静态资源遇到错误：, %s", err)
应为
```
util.Log().Error("导出内置静态资源遇到错误：%s", err)
```

2022-03-13 06:28 UTC, HFO4 commented on bootstrap/static.go
> +			util.Log().Info("创建目录 [%s]...", relPath)
不用单独创建目录，创建文件时调用的`util.CreatNestedFile`会帮你创建。

2022-03-13 06:28 UTC, HFO4 commented on build.sh
> +  yarn --update-checksums
不必在此update checksums， `yarn.lock` checksum 不一致的问题可一次性修复（后续会push）。

2022-03-13 06:28 UTC, HFO4 commented on pkg/cluster/slave_test.go
> +				Body:       io.NopCloser(strings.NewReader("{\"code\":1}")),
关于移除`ioutil`的变更请单独构建PR

2022-03-13 06:28 UTC, HFO4 commented on pkg/util/path.go
> +func ExecPath() string {
可移除，相同功能可以使用`util.RelativePath("")`

2022-03-13 08:54 UTC, Ink-33 commented
好的




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "cloudreve/Cloudreve"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Mar 13, 2022 02:28 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [cloudreve/Cloudreve] 使用go:embed嵌入静态资源 (PR #1107)





 
@HFO4 requested changes on this pull request.
 
 
In .travis.yml:
 &gt;  before_script: -  - statik -src=models -f +  - cd assets +  - mkdir build +  - cd mkdir +  - touch test.html  
可精简为
   - mkdir assets/build   - touch assets/build/test.html  
test.yaml 同理
 
 
In README.md:
 &gt; @@ -85,30 +85,28 @@ cd assets  yarn install  # 开始构建  yarn run build + +# 可选: 删除map文件 +cd build  
可在 README 中移除这段说明，移到文档里。
 
 
In README.md:
 &gt;  ```    #### 嵌入静态资源   -```shell -# 回到项目主目录 -cd ../ - -# 安装 statik, 用于嵌入静态资源 -go get github.com/rakyll/statik - -# 开始嵌入 -statik -src=assets/build/  -include=*.html,*.js,*.json,*.css,*.png,*.svg,*.ico -f -``` +当前版本无需手动嵌入静态资源，请直接进行下一步。  
这段直接移除即可
 
 
In README.md:
 &gt;    #### 编译项目    ```shell +# 回到项目主目录 +cd ../  
可移除
 
 
In bootstrap/static.go:
 &gt;  		}   -		var v staticVersion -		if err := json.Unmarshal(b, &amp;v); err != nil { -			util.Log().Warning("无法解析静态资源文件版本, %s", err) -			return -		} +		StaticFS = &amp;GinFS{} +		StaticFS.(*GinFS).FS = http.FS(embedFS)  
可简化为
 StaticFS = &amp;GinFS{     FS:http.FS(embedFS), }
 
 
In bootstrap/static.go:
 &gt;  	}   -	util.Log().Info("开始导出内置静态资源...") -	walk("/", root) +	// util.Log().Info("开始导出内置静态资源...") +	err = fs.WalkDir(embedFS, ".", walk) +	if err != nil { +		util.Log().Error("导出内置静态资源遇到错误：, %s", err)  
应为
 util.Log().Error("导出内置静态资源遇到错误：%s", err)  
 
In bootstrap/static.go:
 &gt;  			} - +			util.Log().Info("创建目录 [%s]...", relPath)  
不用单独创建目录，创建文件时调用的util.CreatNestedFile会帮你创建。
 
 
In build.sh:
 &gt;      export CI=false      cd $REPO/assets   +  yarn --update-checksums  
不必在此update checksums， yarn.lock checksum 不一致的问题可一次性修复（后续会push）。
 
 
In pkg/cluster/slave_test.go:
 &gt; @@ -70,7 +71,7 @@ func TestSlaveNode_Ping(t *testing.T) {  		mockRequest.On("Request", "POST", "heartbeat", testMock.Anything, testMock.Anything).Return(&amp;request.Response{  			Response: &amp;http.Response{  				StatusCode: 200, -				Body:       ioutil.NopCloser(strings.NewReader("{\"code\":1}")), +				Body:       io.NopCloser(strings.NewReader("{\"code\":1}")),  
关于移除ioutil的变更请单独构建PR
 
 
In pkg/util/path.go:
 &gt; @@ -56,3 +56,10 @@ func RelativePath(name string) string {  	e, _ := os.Executable()  	return filepath.Join(filepath.Dir(e), name)  } + + +// ExecPath 获取可执行文件的路径 +func ExecPath() string {  
可移除，相同功能可以使用util.RelativePath("")
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-03-13 14:30 UTC, Ink-33 commented
已更改，`gofumpt -w .`和移除`ioutil`会单独开pr

2022-03-18 12:03 UTC, HFO4 approved these changes

2022-04-09 12:58 UTC, merged

2022-04-09 12:58 UTC, HFO4 commented
Merged, Thanks!