注册帐号时，如果尚未验证，再发一次验证信  +  修正小bug:未验证显示密码错误
cloudreve/Cloudreve pull request #765
Opened 2021-02-17 20:12 UTC by KusakabeSi

1. 未验证显示密码错误
    1. ```GetUserByEmail```看语意是根据email取得user
    2. 但是 sql 语句却只select已激活user
    3. 导致login.go 拿不到正确的user资讯
    4. 永远只会提示密码错误
2. 注册帐号时，如果尚未验证，再发一次验证信
    1. 因为我这边也是用```GetUserByEmail```拿取user资讯，但是一直拿不到资讯，顺便发现了上面的bug
    2. 现在改成如果已存在的使用者未激活，会这样提示
    3. ![image](https://user-images.githubusercontent.com/73118488/108261924-3651c780-719f-11eb-83b7-2407e8e22532.png)
    3. 并且再发送一次验证码

2021-02-19 04:20 UTC, Misaka13514 approved these changes

2021-02-20 15:19 UTC, KusakabeSi commented
我把这个bug修正也加进这个PR好了，忘记密码以后，重设二步验证设定

2021-02-28 02:13 UTC, HFO4 requested changes

2021-02-28 02:13 UTC, HFO4 commented on models/user.go
> +	result := DB.Set("gorm:auto_preload", true).Where("email = ?", email).First(&user)
`GetUserByEmail` 本意上是根据 Email 查询活跃用户，这里的变更可能会造成连带影响。比如：已被封禁的用户仍然可以通过 WebDAV 操作文件。

2021-02-28 02:13 UTC, HFO4 commented on service/user/login.go
> +	// 重设二步验证设定
我个人认为重设密码不用改重设二步验证代码。二步验证应该跟其他验证方式完全隔离开来，这样才能起到增加安全性的作用。

2021-02-28 15:22 UTC, KusakabeSi commented on models/user.go
> +	result := DB.Set("gorm:auto_preload", true).Where("email = ?", email).First(&user)
但是登入验证那边也是用 ```GetUserByEmail``` 函数。
这边应该要能够取得没有激活的用户，然后提示 ```用户未激活``` ，而不是 ```用户不存在```
变成在这种情境下，就需要新的 ```GetAllUserByEmail``` 函数，来符合上面情境

可是```main.go```上下文有出现这些函数
```go
GetUserByID //不管激活状态
GetActiveUserByOpenID //只取得已激活用户
GetActiveUserByOpenID //只取得已激活用户
GetUserByEmail //只取得已激活用户?????
GetAllUserByEmail //不管激活状态
```
，感觉有些不统一

我提议新增一个 ```GetActiveUserByEmail``` ，来保持上下文语意的统一性
```go
GetUserByID //不管激活状态
GetActiveUserByOpenID //只取得已激活用户
GetActiveUserByOpenID //只取得已激活用户
GetActiveUserByEmail //只取得已激活用户
GetUserByEmail //不管激活状态
```

2021-02-28 15:58 UTC, KusakabeSi commented on service/user/login.go
> +	// 重设二步验证设定
恩...那遗失TOTP装置的话，怎么救援比较好呢?一样用email?
可是忘记密码，或是忘记TOTP都用email的话，还不如两个一起重设
或是用不同的email?这样要大幅改code，而且要改前端，我大概不行了

我刚刚去试了下google和microsoft的作法。他们没有```忘记密码```，而是统一叫做```帐户救援```
帐户救援成功的话，密码和TOTP都会被重置。不过帐户救援的流程相当复杂，有问你安全问题的，问你帐号在哪边注册的，上次登入多久以前，大概什么时间注册的等等

2021-03-01 02:14 UTC, HFO4 commented on models/user.go
> +	result := DB.Set("gorm:auto_preload", true).Where("email = ?", email).First(&user)
我认为做法2比较妥

2021-03-01 02:16 UTC, HFO4 commented on service/user/login.go
> +	// 重设二步验证设定
因为没有提供忘记密码后复杂的验证流程，所以目前设想重设二步验证的工作交给了站点管理员：如果用户丢失验证密钥，则联系管理员提供所需材料，最终由管理员重设。

2021-03-01 05:38 UTC, KusakabeSi commented on service/user/login.go
> +	// 重设二步验证设定
我也认同，TOTP的重置问题，确实不是这个PR该解决的问题
我先revert，然后开一个新的issue，大家一起讨论这个问题比较好

2021-03-01 06:09 UTC, KusakabeSi commented on models/user.go
> +	result := DB.Set("gorm:auto_preload", true).Where("email = ?", email).First(&user)
OK，修改完毕。新的commit已提交

2021-03-02 04:42 UTC, HFO4 approved these changes

2021-03-02 04:43 UTC, merged